package x.test.mapper;

import org.apache.ibatis.annotations.Mapper;
import x.test.model.po.PerformanceAnalyzeConfig;

import java.util.List;

public interface PerformanceAnalyzeConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mg_performance_analyze_config
     *
     * @mbg.generated Thu Feb 20 14:28:34 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mg_performance_analyze_config
     *
     * @mbg.generated Thu Feb 20 14:28:34 CST 2020
     */
    int insert(PerformanceAnalyzeConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mg_performance_analyze_config
     *
     * @mbg.generated Thu Feb 20 14:28:34 CST 2020
     */
    int insertSelective(PerformanceAnalyzeConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mg_performance_analyze_config
     *
     * @mbg.generated Thu Feb 20 14:28:34 CST 2020
     */
    PerformanceAnalyzeConfig selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mg_performance_analyze_config
     *
     * @mbg.generated Thu Feb 20 14:28:34 CST 2020
     */
    int updateByPrimaryKeySelective(PerformanceAnalyzeConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mg_performance_analyze_config
     *
     * @mbg.generated Thu Feb 20 14:28:34 CST 2020
     */
    int updateByPrimaryKey(PerformanceAnalyzeConfig record);

    List<PerformanceAnalyzeConfig> queryAllPerformanceAnalyzeConfig();
}