package x.test.model.po;

import java.util.Date;
import java.util.List;
import java.util.Set;

public class PerformanceAnalyzeConfig {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mg_performance_analyze_config.id
     *
     * @mbg.generated Thu Feb 20 14:28:34 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mg_performance_analyze_config.business_source
     *
     * @mbg.generated Thu Feb 20 14:28:34 CST 2020
     */
    private String businessSource;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mg_performance_analyze_config.event
     *
     * @mbg.generated Thu Feb 20 14:28:34 CST 2020
     */
    private String event;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mg_performance_analyze_config.process
     *
     * @mbg.generated Thu Feb 20 14:28:34 CST 2020
     */
    private String process;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mg_performance_analyze_config.property_type
     *
     * @mbg.generated Thu Feb 20 14:28:34 CST 2020
     */
    private String propertyType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mg_performance_analyze_config.property_value
     *
     * @mbg.generated Thu Feb 20 14:28:34 CST 2020
     */
    private String propertyValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mg_performance_analyze_config.create_time
     *
     * @mbg.generated Thu Feb 20 14:28:34 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mg_performance_analyze_config.update_time
     *
     * @mbg.generated Thu Feb 20 14:28:34 CST 2020
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mg_performance_analyze_config.operate_user
     *
     * @mbg.generated Thu Feb 20 14:28:34 CST 2020
     */
    private String operateUser;

    private List<String> variables;

    private Set<PropertiesPair> properties;

    public List<String> getVariables() {
        return variables;
    }

    public void setVariables(List<String> variables) {
        this.variables = variables;
    }

    public Set<PropertiesPair> getProperties() {
        return properties;
    }

    public void setProperties(Set<PropertiesPair> properties) {
        this.properties = properties;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mg_performance_analyze_config
     *
     * @mbg.generated Thu Feb 20 14:28:34 CST 2020
     */
    public PerformanceAnalyzeConfig(Long id, String businessSource, String event, String process, String propertyType, String propertyValue, Date createTime, Date updateTime, String operateUser) {
        this.id = id;
        this.businessSource = businessSource;
        this.event = event;
        this.process = process;
        this.propertyType = propertyType;
        this.propertyValue = propertyValue;
        this.createTime = createTime;
        this.updateTime = updateTime;
        this.operateUser = operateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mg_performance_analyze_config
     *
     * @mbg.generated Thu Feb 20 14:28:34 CST 2020
     */
    public PerformanceAnalyzeConfig() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mg_performance_analyze_config.id
     *
     * @return the value of mg_performance_analyze_config.id
     *
     * @mbg.generated Thu Feb 20 14:28:34 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mg_performance_analyze_config.id
     *
     * @param id the value for mg_performance_analyze_config.id
     *
     * @mbg.generated Thu Feb 20 14:28:34 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mg_performance_analyze_config.business_source
     *
     * @return the value of mg_performance_analyze_config.business_source
     *
     * @mbg.generated Thu Feb 20 14:28:34 CST 2020
     */
    public String getBusinessSource() {
        return businessSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mg_performance_analyze_config.business_source
     *
     * @param businessSource the value for mg_performance_analyze_config.business_source
     *
     * @mbg.generated Thu Feb 20 14:28:34 CST 2020
     */
    public void setBusinessSource(String businessSource) {
        this.businessSource = businessSource == null ? null : businessSource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mg_performance_analyze_config.event
     *
     * @return the value of mg_performance_analyze_config.event
     *
     * @mbg.generated Thu Feb 20 14:28:34 CST 2020
     */
    public String getEvent() {
        return event;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mg_performance_analyze_config.event
     *
     * @param event the value for mg_performance_analyze_config.event
     *
     * @mbg.generated Thu Feb 20 14:28:34 CST 2020
     */
    public void setEvent(String event) {
        this.event = event == null ? null : event.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mg_performance_analyze_config.process
     *
     * @return the value of mg_performance_analyze_config.process
     *
     * @mbg.generated Thu Feb 20 14:28:34 CST 2020
     */
    public String getProcess() {
        return process;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mg_performance_analyze_config.process
     *
     * @param process the value for mg_performance_analyze_config.process
     *
     * @mbg.generated Thu Feb 20 14:28:34 CST 2020
     */
    public void setProcess(String process) {
        this.process = process == null ? null : process.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mg_performance_analyze_config.property_type
     *
     * @return the value of mg_performance_analyze_config.property_type
     *
     * @mbg.generated Thu Feb 20 14:28:34 CST 2020
     */
    public String getPropertyType() {
        return propertyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mg_performance_analyze_config.property_type
     *
     * @param propertyType the value for mg_performance_analyze_config.property_type
     *
     * @mbg.generated Thu Feb 20 14:28:34 CST 2020
     */
    public void setPropertyType(String propertyType) {
        this.propertyType = propertyType == null ? null : propertyType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mg_performance_analyze_config.property_value
     *
     * @return the value of mg_performance_analyze_config.property_value
     *
     * @mbg.generated Thu Feb 20 14:28:34 CST 2020
     */
    public String getPropertyValue() {
        return propertyValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mg_performance_analyze_config.property_value
     *
     * @param propertyValue the value for mg_performance_analyze_config.property_value
     *
     * @mbg.generated Thu Feb 20 14:28:34 CST 2020
     */
    public void setPropertyValue(String propertyValue) {
        this.propertyValue = propertyValue == null ? null : propertyValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mg_performance_analyze_config.create_time
     *
     * @return the value of mg_performance_analyze_config.create_time
     *
     * @mbg.generated Thu Feb 20 14:28:34 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mg_performance_analyze_config.create_time
     *
     * @param createTime the value for mg_performance_analyze_config.create_time
     *
     * @mbg.generated Thu Feb 20 14:28:34 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mg_performance_analyze_config.update_time
     *
     * @return the value of mg_performance_analyze_config.update_time
     *
     * @mbg.generated Thu Feb 20 14:28:34 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mg_performance_analyze_config.update_time
     *
     * @param updateTime the value for mg_performance_analyze_config.update_time
     *
     * @mbg.generated Thu Feb 20 14:28:34 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mg_performance_analyze_config.operate_user
     *
     * @return the value of mg_performance_analyze_config.operate_user
     *
     * @mbg.generated Thu Feb 20 14:28:34 CST 2020
     */
    public String getOperateUser() {
        return operateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mg_performance_analyze_config.operate_user
     *
     * @param operateUser the value for mg_performance_analyze_config.operate_user
     *
     * @mbg.generated Thu Feb 20 14:28:34 CST 2020
     */
    public void setOperateUser(String operateUser) {
        this.operateUser = operateUser == null ? null : operateUser.trim();
    }
}